version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "monthly"
      time: "00:00"
      timezone: "Asia/Riyadh"
      update-types: ["version-update:semver-patch"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "monthly"
      time: "00:00"
      timezone: "Asia/Riyadh"
