version: 2
updates:
  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
      timezone: "03:00 UTC"
    assignees:
      - "Yokozuna59"
    labels:
      - "pip"
      - "dependencies"
      - "automation"
    reviewers:
      - "Yokozuna59"
    target-branch: "master"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
      timezone: "03:00 UTC"
    assignees:
      - "Yokozuna59"
    labels:
      - "github-actions"
      - "dependencies"
      - "automation"
    reviewers:
      - "Yokozuna59"